### ISSUE TITLE
Static links to sections of the ezEML User Guide

### ISSUE THREAD

**Issue by clnsmth** [PASTAplus/metadata-eml#81]
Hi @jon-ide. Currently, URLs to sections of the ezEML User Guide contain version specific information. This creates a maintenance issue for web-x, where the URLs become outdated when a new version of ezEML is released. A static link to sections of the ezEML User Guide would be preferred (if possible).

**Comment by jon-ide** [comment]
The version query string is a standard trick for getting browsers to load the current version. Otherwise, if the browser has already cached the page, it won't get it again, and it may display a stale version. With the version in the query string, the browser will only consider that it has cached it if it matches the query string as well as the static link. ezEML pays no attention to the query string; it's just there to fool the browser.

So the upshot is that you can safely ignore it when posting links. Just leave it off.
